### Transforming code into Idiomatc Python

In [7]:
for i in [0,1,2,3,4,5]:
    print(i**2,end=" ")

0 1 4 9 16 25 

In [8]:
for i in range(6):
    print(i**2,end=" ")

0 1 4 9 16 25 

### Looping over a Collection

In [10]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end=" ")

red green yellow purple 

In [11]:
for color in colors:
    print(color,end=" ")

red green yellow purple 

### Looping Backwards

In [12]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=" ")

purple yellow green red 

In [13]:
for colors in reversed(colors):
    print(color,end=" ")

purple purple purple purple 

### Looping in Sorted List

In [14]:
colors = ['red','green','yellow','purple']
for color in sorted(colors):
    print(color,end=" ")

green purple red yellow 

In [15]:
colors = ['red','green','yellow','purple']
for color in sorted(colors,reverse=True):
    print(color,end=" ")

yellow red purple green 

### Pandas

In [16]:
import pandas as pd

In [19]:
dt = {'Id':[11,12,13,14,15],
      'first_name':['A','B','C','D','E'],
      'company':['aa','bb','cc','dd','ee'],
      'address':['Hyd','Hyd','Hyd','Hyd','Hyd']}
mydt = pd.DataFrame(dt)

In [20]:
print(mydt)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [21]:
import os

In [26]:
os.chdir("Documents") 

In [27]:
mydt.to_csv("workingfile.csv",index = False)

## Reading the data from CSV file

In [28]:
mydata = pd.read_csv('workingfile.csv')

In [29]:
print(mydata)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [30]:
mydata1 = pd.read_csv('workingfile.csv',names=["cosId","Name","Company","Address"])

In [31]:
print(mydata1)

  cosId        Name  Company  Address
0    Id  first_name  company  address
1    11           A       aa      Hyd
2    12           B       bb      Hyd
3    13           C       cc      Hyd
4    14           D       dd      Hyd
5    15           E       ee      Hyd


In [37]:
mydata2 = pd.read_csv('workingfile.csv',skiprows=1,names=["cosId","Name","Company","Address"])

In [38]:
print(mydata2)

   cosId Name Company Address
0     11    A      aa     Hyd
1     12    B      bb     Hyd
2     13    C      cc     Hyd
3     14    D      dd     Hyd
4     15    E      ee     Hyd


In [41]:
pwd

'C:\\Users\\221\\Documents'

## Numpy

In [1]:
import numpy as np

In [2]:
li = [1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [3]:
array = np.array(li)
print(array)

[1 2 3 4 5]


In [4]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2 = np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(2, 3)
(3, 2)


In [5]:
a1 = np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [8]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
